name: Doc's CI/CD
on:
  workflow_call:
    inputs:
      version:
        description: "the new version after semantic release"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: is main?
        if: contains(env.BRANCH_NAME, 'main') == false
        run: exit -1

      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_ACCESS_TOKEN }}

      - name: Installations
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/lulav/pdoc.git@master

      - name: make documentation
        run: |
          chmod +x citros_data_analysis_doc.sh
          ./citros_data_analysis_doc.sh

      # - name: debug-stage
      #   run: |
      #     cd docusaurus
      #     ls -all

      - name: create docusuros version
        run: |
          cd docusaurus
          yarn install
          yarn docusaurus docs:version ${{inputs.version}}

      - name: Stage and push new files
        run: |
          git pull
          git config --global user.email "vovacooper@gmail.com"
          git config --global user.name "vovacooper"          
          git add -A
          git commit -m "docs(docusaurus): action to make docs"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SEMANTIC_RELEASE_ACCESS_TOKEN }}
          branch: ${{ github.ref }}
