name: testing
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Installations
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/lulav/pdoc.git@master

      # - name: make documentation
      #   run: |
      #     chmod +x citros_data_analysis_doc.sh
      #     ./citros_data_analysis_doc.sh
      
      name: make commands documentation
        run: |
          chmod +x citros_commands
          ./citros_commands

      - name: Stage and push new files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "docs(docusaurus/docs/data_analysis/documentation): action to make docs"
          git push