name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_ACCESS_TOKEN }}

      - name: Python Semantic Release
        id: semantic
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.SEMANTIC_RELEASE_ACCESS_TOKEN }}

      - name: output
        if: steps.semantic.outputs.released == 'true'
        run: |
          echo ${{ steps.semantic.outputs.released }}
          echo ${{ steps.semantic.outputs.tag }}
          echo ${{ steps.semantic.outputs.version }}

      - uses: ./.github/workflows/generate-docs.yaml
