name: testing
on: 
  push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: python:3.10
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f tests/data_analysis_tests/requirements_test.txt ]; then pip install -r tests/data_analysis_tests/requirements_test.txt; fi
          python -m build
          python -m pip install .

      - name: Populate PostgreSQL database
        # Runs a script that creates a PostgreSQL table and populates
        # the table with data.
        working-directory: ./tests/data_analysis_tests
        run: echo | python create_table.py
      - name: Test with pytest
        # Run tests
        working-directory: ./tests/data_analysis_tests
        run: |
          pytest